### ISSUE TITLE
crash with latest 1.4-stable tmodloader update

### ISSUE THREAD

**Issue by wojciechsacewicz** [Chicken-Bones/InfiniteMunitions#1]
crash log in comment since i posted the wrong crash log first time...

**Comment by wojtulinka** [comment]
[21:54:57] [.NET ThreadPool Worker/INFO] [tML]: Initializing: InfiniteMunitions (Infinite Munitions) v1.0.1
[21:54:57] [.NET ThreadPool Worker/WARN] [tML]: Silently Caught Exception: 
System.MissingFieldException: Field not found: 'Terraria.Item.UseSound'.
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETCore30Platform.CompileMethodHook(IntPtr jit, IntPtr corJitInfo, CORINFO_METHOD_INFO& methodInfo, UInt32 flags, Byte*& nativeEntry, UInt32& nativeSizeOfCode)
   at System.Runtime.CompilerServices.RuntimeHelpers.PrepareMethod(RuntimeMethodHandleInternal method, IntPtr* pInstantiation, Int32 cInstantiation)
   at System.Runtime.CompilerServices.RuntimeHelpers.PrepareMethod(RuntimeMethodHandleInternal method, IntPtr* pInstantiation, Int32 cInstantiation)
   at System.Runtime.CompilerServices.RuntimeHelpers.PrepareMethod(RuntimeMethodHandle method, RuntimeTypeHandle[] instantiation)
   at System.Runtime.CompilerServices.RuntimeHelpers.PrepareMethod(RuntimeMethodHandle method)
   at Terraria.ModLoader.Core.AssemblyManager.ForceJITOnMethod(MethodBase method) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 379
   at Terraria.ModLoader.Core.AssemblyManager.<>c__DisplayClass24_0.<JITAssemblies>b__1(MethodBase method) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 354
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

[21:54:57] [.NET ThreadPool Worker/WARN] [tML]: Silently Caught Exception: 
System.MissingFieldException: Field not found: 'Terraria.Item.UseSound'.
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETCore30Platform.CompileMethodHook(IntPtr jit, IntPtr corJitInfo, CORINFO_METHOD_INFO& methodInfo, UInt32 flags, Byte*& nativeEntry, UInt32& nativeSizeOfCode)
   at System.Runtime.CompilerServices.RuntimeHelpers.PrepareMethod(RuntimeMethodHandleInternal method, IntPtr* pInstantiation, Int32 cInstantiation)
   at System.Runtime.CompilerServices.RuntimeHelpers.PrepareMethod(RuntimeMethodHandleInternal method, IntPtr* pInstantiation, Int32 cInstantiation)
   at System.Runtime.CompilerServices.RuntimeHelpers.PrepareMethod(RuntimeMethodHandle method, RuntimeTypeHandle[] instantiation)
   at Terraria.ModLoader.Core.AssemblyManager.ForceJITOnMethod(MethodBase method) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 379
   at Terraria.ModLoader.Core.AssemblyManager.<>c__DisplayClass24_0.<JITAssemblies>b__1(MethodBase method) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 354
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

[21:54:57] [.NET ThreadPool Worker/WARN] [tML]: Silently Caught Exception: 
Terraria.ModLoader.Exceptions.JITException: 
In InfiniteMunitions.EndlessHealingPotion.SetDefaults, Field not found: 'Terraria.Item.UseSound'.
In InfiniteMunitions.EndlessManaPotion.SetDefaults, Field not found: 'Terraria.Item.UseSound'.

   at Terraria.ModLoader.Core.AssemblyManager.JITAssemblies(IEnumerable`1 assemblies, PreJITFilter filter) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 374
   at Terraria.ModLoader.Core.AssemblyManager.JITMod(Mod mod) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 332
   at Terraria.ModLoader.ModContent.<>c.<Load>b__41_0(Mod mod) in tModLoader\Terraria\ModLoader\ModContent.cs:line 305
   at Terraria.ModLoader.ModContent.LoadModContent(CancellationToken token, Action`1 loadAction) in tModLoader\Terraria\ModLoader\ModContent.cs:line 369
   at Terraria.ModLoader.ModContent.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 304
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 120
   at Terraria.ModLoader.ModLoader.<>c__DisplayClass45_0.<BeginLoad>b__0() in tModLoader\Terraria\ModLoader\ModLoader.cs:line 102
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

[21:54:57] [.NET ThreadPool Worker/ERROR] [tML]: An error occurred while loading InfiniteMunitions
It has been detected that this mod was built for tModLoader v0.12
However, you are using tModLoader v2022.5.103.3
The mod will need to be updated to match the current tModLoader version, or may be incompatible with the version of some of your other mods. Click the 'Open Web Help' button to learn more.
The mod(s) have been automatically disabled.
Terraria.ModLoader.Exceptions.JITException: 
In InfiniteMunitions.EndlessHealingPotion.SetDefaults, Field not found: 'Terraria.Item.UseSound'.
In InfiniteMunitions.EndlessManaPotion.SetDefaults, Field not found: 'Terraria.Item.UseSound'.

   at Terraria.ModLoader.Core.AssemblyManager.JITAssemblies(IEnumerable`1 assemblies, PreJITFilter filter) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 374
   at Terraria.ModLoader.Core.AssemblyManager.JITMod(Mod mod) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 332
   at Terraria.ModLoader.ModContent.<>c.<Load>b__41_0(Mod mod) in tModLoader\Terraria\ModLoader\ModContent.cs:line 305
   at Terraria.ModLoader.ModContent.LoadModContent(CancellationToken token, Action`1 loadAction) in tModLoader\Terraria\ModLoader\ModContent.cs:line 369
   at Terraria.ModLoader.ModContent.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 304
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 120
[21:54:57] [.NET ThreadPool Worker/INFO] [tML]: Disabling Mod: InfiniteMunitions

**Comment by Chicken-Bones** [comment]
Updated! 

It seems in all my time developing tModLoader, I forgot I had actual mods.

**Comment by wojtulinka** [comment]
thanks mate! love your mod<33
